# Required by GitHub Pages if/when a repo doesn’t have a remote named `origin` pointing to a GitHub
# repo. Which is how I have my local repo set up. (In my case I‘ve named the remote gh-fundingcircle
# as in general I think something with `gh` or `github` jives better than `origin` with the ethos of
# Git.)
repository: FundingCircle/fc4-framework

# GitHub pages could derive these from the repo for us, but I prefer to override them with these
# values, for now, because the name and description of the repo are temporarily a little out of sync
# with the newer language in these docs.
title: FC4
description: A tool for authoring C4 diagrams

# This is the default theme for GitHub Pages; I’m just leaving this here as a form of documentation
# in case someone is trying to figure out what theme this site is using, as I found it wasn’t easy
# for me to figure this out.
theme: jekyll-theme-primer

plugins:
  - jekyll-redirect-from

permalink: :pretty

# See https://github.com/benbalter/jekyll-optional-front-matter#configuration
optional_front_matter:
  remove_originals: true

# We’re using kramdown so we can use parse_block_html
markdown: kramdown

kramdown:
  parse_block_html: true
